dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

services:
  - docker

before_script:
  - make build python_bin=python3
  - make run

install: pip3 install -r requirements.txt
script: make test python_bin=python3 nosetests_bin=nosetests
