language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

services:
  - docker

before_script:
  - make build python_bin=python3
  - make run

install: pip install -r requirements.txt
script: make test
