version: '3'
services:
  dex:
    build:
      context: .
      dockerfile: ${DEX_DOCKER_FILE}
    links:
      - "openldap"
    container_name: ${DEX_DOCKER_IMAGE_NAME}
    ports:
      - "5557:5557"
      - "5556:5556"
    restart: on-failure
    depends_on:
      - openldap
  openldap:
    build:
      context: .
      dockerfile: docker_files/Dockerfile_OpenLDAP
    container_name: dex-openldap
    environment:
      - LDAP_ORGANISATION=MondoCorp
      - LDAP_DOMAIN=example.org
      - LDAP_ADMIN_PASSWORD=password
    healthcheck:
      test: ["CMD", "/bin/bash", "/usr/local/bin/openldap_healthcheck.sh"]
      interval: 5s
      timeout: 2s
      retries: 5
