FROM quay.io/dexidp/dex:v2.14.0

RUN mkdir -p /etc/dex/tls

COPY docker_files/dex_tls/ /etc/dex/tls/.
COPY docker_files/config/dev_v2_11_0.yaml /etc/dex.yaml

ENTRYPOINT /usr/local/bin/dex serve /etc/dex.yaml
